# These are all the cops that are enabled in the default configuration.
AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  # If .ruby-version exists and it contains an MRI version it is used.
  # Otherwise we fallback to the oldest officially supported Ruby version.
  TargetRubyVersion: ~
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*.js"
    - "node_modules/**/*.spec"

Layout/AccessModifierIndentation:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  Enabled: true

Style/AndOr:
  Enabled: false

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockComments:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  Enabled: false
