# These are all the cops that are enabled in the default configuration.
AllCops:
  DisabledByDefault: true
  # If .ruby-version exists and it contains an MRI version it is used.
  # Otherwise we fallback to the oldest officially supported Ruby version.
  TargetRubyVersion: ~
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"

Style/AccessModifierIndentation:
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AlignArray:
  Enabled: true

Style/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Enabled: true

Style/AndOr:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockEndNewline:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

Style/CaseEquality:
  Enabled: true

Style/CaseIndentation:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/CommentIndentation:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/DotPosition:
  Enabled: true

Style/ElseAlignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: true

Style/EmptyLinesAroundClassBody:
  Enabled: true

Style/EmptyLinesAroundModuleBody:
  Enabled: true

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/Encoding:
  Enabled: true
  EnforcedStyle: never

Style/HashSyntax:
  Enabled: true

Style/IndentationConsistency:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/LeadingCommentSpace:
  Enabled: true

Style/MethodCallParentheses:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundKeyword:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Enabled: true

Style/Tab:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Lint/EndAlignment:
  AlignWith: variable
  Enabled: true
